---
title: "EDA Airbnb"
author: "Antonio Fernández Cáceres"
date: "18/11/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Cargar Librerías

```{r}
library(caret)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggmap)
library(RgoogleMaps)
library(leaps)
library(stringr)
library(readr)
library(ggfortify)
library(batman)
library(ggcorrplot)
```

```{r loadData}
RawData <- read.csv(file = '../00_DatosOriginales/listings.csv', header = TRUE)
```

## 2. Separación Train-Test

```{r split}

set.seed(12345)
inTraining <- createDataPartition(pull(RawData, neighbourhood_group_cleansed),
                                  p = .7, list = FALSE, times = 1)
data <- slice(RawData, inTraining) # Renombrado "data" por conveniencia
data_test <- slice(RawData, -inTraining)

```

## 3. Conversión de tipos

```{r typeConversion}
data$host_since <- as.Date(data$host_since)
data$host_is_superhost <- to_logical(data$host_is_superhost)
data$price<-parse_number(data$price)
```

## 4. Sustitución de NA's
```{r nas}



```

## 6. Exploración de amenities


```{r ExtractAmenities}

head(data$amenities)
str(data$amenities)

amenities <- c()

common <- unique(c('wifi', 'dryer', 'essentials', 'kitchen', 'heating', 'long term', 'hangers', 'washer', 'iron', 'tv', 'shampoo', 'hot water', 'air conditioning', 'dedicated workspace', 'dishes and silverware', 'parking', 'refrigerator', 'cooking basics', 'elevator', 'microwave', 'coffee', 'bed linens', 'alarm', 'stove', 'oven', 'fire extinguisher', 'extra pillows and blankets', 'first aid kit', 'dishwasher', 'host greets you', 'lock', 'cable', 'shower gel', 'luggage dropoff allowed', 'patio', 'darkening shades', 'room', 'private entrance', 'crib', 'breakfast', 'freezer', 'clothing storage', 'soap', 'cleaning products', 'dining table', 'drying rack for clothing', 'ethernet', 'bathtub', 'toaster', 'security camera', 'wine glasses', 'hot water kettle', 'single level home', 'backyard', 'pack ', 'travel crib', 'laundromat nearby', 'high chair', ' closet', 'children', 'pool', 'portable fans', 'nespresso', 'cleaning before checkout', 'building staff', 'babysitter', 'conditioner', 'books and toys', 'gym', 'bidet', 'baking sheet', 'mini fridge', 'window guards', 'free washer', 'dinnerware', 'indoor fireplace', 'keypad', 'baby bath', 'hot tub', 'ceiling fan', 'pour', 'outdoor furniture', 'ps', 'sound system', ' table', 'outlet covers', 'safe', 'beachfront', 'wardrobe', 'outdoor dining area', 'bathroom essentials', 'bedroom comforts', 'changing table', 'office', 'outdoor shower', 'board games', 'induction', 'bbq grill', 'heater', 'ski', 'desk', 'netflix', 'hdtv', 'baby safety gates', ' hdtv', 'table corner guards', 'game console', 'barbecue utensils', 'rice maker', 'ev charger', 'amazon prime', 'dresser and closet', 'bread maker', 'window ac unit', 'beach essentials', 'dresser', 'closet', 'fireplace guards', 'mosquito net', 'paid washer', 'self check', 'chromecast', 'piano', 'lake access', 'bikes', 'record player', 'baby monitor', 'free washer', 'pets allowed', 'sauna', 'trash compactor', 'books and toys for ages 0', 'monitor', 'hbo max', 'jab', 'books and toys for ages 2', 'apple tv', 'garage', 'smoking allowed', 'bed sheets and pillows', 'laundry', 'fire pit', 'gel', 'room service', 'toiletries', 'waterfront', 'concierge', 'minibar', 'onsite bar', 'paid washer', 'airport shuttle', 'garden', 'horno', 'limited housekeeping ', 'nintendo', 'onsite restaurant', 'ping pong table', 'roku', 'suitable for events', 'books and toys for ages 10+ years old', 'books and toys for ages 5', 'vitrocer', 'linens', 'xbox one', 'air fryer', 'alexa', 'all inclusive', 'bottled water', 'cd player', 'fitness center', 'house bikes', 'housekeeping','mini cadena', 'shared indoor olympic', 'shared outdoor olympic', 'slippers', 'spa'))

data2 <- data
data2 <- data2 %>% mutate(pricePP = ifelse(accommodates!=0,price/accommodates,price))

for (row in 1:nrow(data2)) {
  my_string<-tolower(str_split(data$amenities[row], '[[:punct:]]')[[1]])
  for (com in common){
    for (s in my_string){
      if(str_detect(s,com)){
         my_string[my_string==s]<-com
      }
    }
  }
  
  data2$amenities[row] <- tolower(toString(my_string[(my_string!= "") & (my_string!= " ")]))
  amenities<-c(amenities, data2$amenities[row])
}

write.csv(data2,'listings_am.csv')

am <- data.frame(amenities)
amenities <- as.data.frame(am %>% group_by(amenities) %>% summarize(n = n()) %>% arrange(desc(n)))

amenities <- amenities[amenities$amenities %in% common,]

colnames(amenities) <- c("name", "count")

#write.csv(amenities,'amenities.csv')

```

```{r EDAamenities}

data2 <- read.csv('listings_am.csv')
amenities <- read.csv('amenities.csv')
amenities$X <- NULL

meanPriceByAmenity <- c()

data2$amenities <- tolower(data2$amenities)
data2 <- data2[data2$price!=0,]

for (element in 1:nrow(amenities)){
  meanPriceByAmenity <- mean(data2[str_detect(data2$amenities,amenities$name[element]), "pricePP"])
  amenities$meanprice[element] <- meanPriceByAmenity
}

amenities <- amenities %>% arrange(desc(meanprice))

amenities

```


```{r amenitiesScore}

max_price <- max(amenities$meanprice)
amenities <- amenities %>% mutate(ratio = meanprice/max(na.omit(meanprice)))
amenities$ratio <- amenities$ratio/max(amenities$meanprice)

amenities = na.omit(amenities)
amenities <- amenities %>% mutate(freq = nrow(data2)/count) %>% arrange(desc(freq), desc(meanprice))
amenities

data2$am_score <- 0

for (row in 1:nrow(data2)){
  points <- 0
  counter <- 0
  for (element in 1:nrow(amenities)){
    if(str_detect(data2$amenities[row],amenities$name[element])){
      points <- points + log10(nrow(data2)/amenities$count[element])
      counter <- counter + 1
    }
  }
  data2$am_score[row] <- points*data2$price[row]
}

hist(data2$am_score)
ggplot(data2, aes(x=am_score)) + geom_histogram() + xlim(c(0,5000))


data3 <- data2 %>% mutate(pricePP = price/accommodates)
plot(data3$pricePP, data3$am_score)
abline(lm(data3$am_score ~ data3$pricePP))  

```


```{r regressionTest}

umbral <- 150
plazas <- 10
data3 <- data3[data3$pricePP<umbral & data3$accommodates<=plazas,]

data3[grep("wanda", tolower(data3$description)) & data3$room_type=="Shared room" & data3$neighbourhood_group_cleansed=="San Blas - Canillejas",c("neighbourhood_group_cleansed","neighbourhood_cleansed")] <- "Wanda Metropolitano"

model<-lm(log(price) ~ accommodates+bedrooms+neighbourhood_cleansed + am_score + review_scores_rating + latitude +availability_365+room_type+host_since+review_scores_location+review_scores_value+review_scores_cleanliness+minimum_nights, data = data3)

model <- lm_fit <- lm(log(price)~latitude+accommodates*beds*bedrooms+host_since+availability_30+room_type+neighbourhood_cleansed+review_scores_rating+review_scores_location+review_scores_value+review_scores_cleanliness+number_of_reviews+number_of_reviews+number_of_reviews_l30d+maximum_nights_avg_ntm+maximum_nights+minimum_minimum_nights+maximum_maximum_nights+maximum_nights_avg_ntm+availability_30+instant_bookable+property_type+host_acceptance_rate+bathrooms_text+host_response_rate+host_location+host_response_time+host_identity_verified+am_score, data=data3)

summary(model)
autoplot(model)

plot(data3$pricePP, data3$am_score)
abline(lm(data3$am_score ~ data3$pricePP))

head(data3 %>% arrange(desc(am_score)) %>% select(price, am_score, amenities),10)

```