---
title: "Memoria Fundamentos de Analisis de Datos."
author: "Alvaro Simón Merino, Antonio Fernández Cáceres, Katsiaryna Zaitsava"
date: "13/11/2021"
output:
  html_document:
    theme: united
    code_folding: "hide"
    toc: yes
    toc_float: yes
---

---

## 00 Introducción a la práctica y librerías

Para la práctica hemos seleccionado una base de datos obtenida de insideairbnb.com con los alquileres de AirBnb de Madrid. Esta base de datos es de dominio público y consta de 22 variables con 18909 observaciones.

La base de datos puede descargarse en el siguiente enlace: http://insideairbnb.com/get-the-data.html


Las librerias usadas para esta práctica son las siguientes:

 - dplyr
 - ggplot2
 - knitr
 - tidyr
 
```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(knitr)
library(tidyr)
```
<br/>

## 01 Definición de objetivos
Dado que la base de datos elegida está relacionado con el alquiler de viviendas, consideramos la variable "price", la cual representa el valor del precio del alquiler, como la variable objetivo de la práctica.
<br/>

### Objetivos generales
- Analizar las variables de la base de datos seleccionada para su comprensión y posterior estudio.
- Aplicar el módelo de regresión lineal múltiple para inferir la variable "price" seleccionada, que corresponde al precio de la vivienda.
<br/>

### Objetivos específicos
1. Separar de los datos en 2 grupos de datos: trainning, control y testing.
    - El grupo training + control contiene el 80% de los datos, con el cual entrenaremos el modelo. 
    - El grupo test contiene el 20% de los datos y se dejará como conjunto aislado hasta el final de la práctica como simulación de datos reales.

2. Realizar un análisis exploratorio inicial de cada una de las variables de la base de datos.
    - Se llevará a cabo separando las variables categóricas de las cualitativas para su posterior estudio.
    
3. Imputar las variables faltantes de la base de datos previo estudio
4. Aplicar las transformaciones necesarias a cada una de las variables.
5. Entrenar el modelo matemático de regresión múltiple para la predicción de la varaible precio.
<br/>

## 02 Carga y aislamiento de datos TEST

<br/>

## 03 Análisis exploratorio inicial. EDA
En este apartado realizamos un primer análisis para comprender las variables y el estado original en el que se encuentra la base de datos.

<br/>

### Descripción de variables

<br/>

### A. Análisis univariante cuantitativo

<br/>

### B. Analisis univariante cualitativo

<br/>

### c. Análisis multivariante cuantitativo

<br/>

### c. Análisis multivariante cualitativo

<br/>

## 04 Detección, tratamiento e imputación de datos faltantes
### Análisis previo

<br/>

#### Imputación de las variables contínuas:

<br/>

### Imputación de variables

<br/>

## 05 Transformación de variables

<br/>

### Transformación de variables cuantitativas

<br/>

### Transformación de variables cualitativas

<br/>

### Trasformaciṕn de variables cualitativas

<br/>

### Resumen final

<br/>

## 06 Comprobación de los datos

<br/>

## 07 Ajuste, interpretación y diagnosis del modelo de regresión lineal múltiple

<br/>

### Entrenamiento del modelo ML con todas las variables

<br/>


